// <auto-generated />
namespace ExpenseManger.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatecategory2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecategory2));
        
        string IMigrationMetadata.Id
        {
            get { return "201512150654208_update category 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
